build_image:
  name: shipimg/ubuntu1404_go
  privileged: false

cache: false

language: go

go:
  - 1.4
  - 1.3
  - 1.2


branches:
  only:
    - master
    - develop

before_install:
  - source $HOME/.gvm/scripts/gvm
  - gvm install go$SHIPPABLE_GO_VERSION
  - gvm use go$SHIPPABLE_GO_VERSION
  - export GOPATH=$SHIPPABLE_GOPATH
  - export PATH=$PATH:$GOPATH/bin


script:
  - go test -v

after_script:

after_success:

after_failure:
